// Copyright 2025 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#define BOOTMAGIC_ROW    6
#define BOOTMAGIC_COLUMN 5

/* spi config for eeprom and pmw3360 sensor */
#define SPI_DRIVER        SPID1
#define SPI_SCK_PIN       A5
#define SPI_SCK_PAL_MODE  5
#define SPI_MOSI_PIN      A7
#define SPI_MOSI_PAL_MODE 5
#define SPI_MISO_PIN      A6
#define SPI_MISO_PAL_MODE 5

#define EXTERNAL_EEPROM_SPI_SLAVE_SELECT_PIN A4
#define EXTERNAL_EEPROM_SPI_CLOCK_DIVISOR    8

#define DISPLAY_CS_PIN  A2
#define DISPLAY_DC_PIN  A1
#define DISPLAY_RST_PIN A3

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 600000
#define QUANTUM_PAINTER_TASK_THROTTLE   10
#ifndef QUANTUM_PAINTER_NUM_IMAGES
#    define QUANTUM_PAINTER_NUM_IMAGES 12
#endif // QUANTUM_PAINTER_NUM_IMAGES
#ifndef QUANTUM_PAINTER_SUPPORTS_256_PALETTE
#    define QUANTUM_PAINTER_SUPPORTS_256_PALETTE TRUE
#endif // QUANTUM_PAINTER_SUPPORTS_256_PALETTE
#ifndef QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS
#    define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
#endif // QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS

#define BACKLIGHT_PWM_DRIVER  PWMD5
#define BACKLIGHT_PWM_CHANNEL 1
#define BACKLIGHT_PAL_MODE    2
#define BACKLIGHT_PIN         A0

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define LAYER_MAP_REMAPPING
#define LAYER_MAP_COLS 23
#define LAYER_MAP_ROWS 7

#define AUDIO_PIN          B1
#define AUDIO_PWM_DRIVER   PWMD3
#define AUDIO_PWM_CHANNEL  4
#define AUDIO_PWM_PAL_MODE 2
#define AUDIO_CLICKY

#define AUDIO_POWER_CONTROL_PIN B10
